In [1]:
from pylib.setup import *
setup_notebook()

!pip install comext_wrapper --upgrade --quiet

from comext_wrapper import ServicesApi
api = ServicesApi()

# Services trade API — lookup notebook

Use this notebook to explore the Eurostat BOP_ITS6_DET dataset (EU international trade in services, EBOPS 2010) before building queries.

Three tools:
- `api.info()` — dataset overview and dimension summary
- `api.codes(dimension, search=...)` — browse valid codes
- `api.get_data(...)` — fetch data as a DataFrame

---
## 1. Dataset overview

In [2]:
api.info() ;

Dataset : BOP_ITS6_DET
Name    : International trade in services (since 2010) (BPM6)
Updated : 2014-12-18T15:59:07+0100

dimension  # codes first code            first label      last code                               last label
     freq       12          P           Pluri-annual             A3                                Triannual
 currency      194      TOTAL Total (all currencies)            UNK                                  Unknown
 bop_item      383         CA        Current account FA__P__F5__JPY Financial account; portfolio investment;
 stk_flow      194      TOTAL                  Total            UNK                                  Unknown
  partner      488        EUR                 Europe            UNK                                  Unknown
      geo     4292        EUR                 Europe            UNK                                  Unknown

Key order: freq.currency.bop_item.stk_flow.partner.geo

---
## 2. Browse dimension codes

Valid dimensions: `freq`, `currency`, `bop_item`, `stk_flow`, `partner`, `geo`

In [3]:
# Flow and frequency options
print("--- stk_flow ---")
display(api.codes("stk_flow"))

print("--- freq ---")
display(api.codes("freq"))

--- stk_flow ---

              id                                              label
0          TOTAL                                              Total
1    CRE_DEB_AVG                      Average of credits and debits
2    CRE_DEB_SUM                          Sum of credits and debits
3            CRE                                             Credit
4            DEB                                              Debit
..           ...                                                ...
189         N_KA  Net other changes in the volume of assets/liab...
190        NE_LE         Net liabilities (liabilities minus assets)
191      HUMD_PC                                       Humidity (%)
192          NSP                                      Not specified
193          UNK                                            Unknown

[194 rows x 2 columns]

--- freq ---

     id                    label
0     P             Pluri-annual
1     A                   Annual
2     S  Half-yearly, semesterly
3     Q                Quarterly
4     M                  Monthly
5     W                   Weekly
6     B    Daily - business week
7     D                    Daily
8     H                   Hourly
9     I   Irregular / A-periodic
10  NAP           Not applicable
11   A3                Triannual

In [4]:
# Available currencies
api.codes("currency")

          id                                              label
0      TOTAL                             Total (all currencies)
1        EUR                                               Euro
2    EUR_FOR         Euro, if Euro is not the national currency
3    MIO_EUR                                       Million euro
4        BGN                                      Bulgarian lev
..       ...                                                ...
189      NAT  National currency (former currencies of the eu...
190      FOR                                   Foreign currency
191      OTH                                   Other currencies
192      NAP                                     Not applicable
193      UNK                                            Unknown

[194 rows x 2 columns]

In [5]:
# Partner aggregates
api.codes("partner", aggregates_only=True)

            id                                      label
0          EUR                                     Europe
1    EU27_2020  European Union - 27 countries (from 2020)
2         EU28  European Union - 28 countries (2013-2020)
3    EU27_2007  European Union - 27 countries (2007-2013)
4         EU25  European Union - 25 countries (2004-2006)
..         ...                                        ...
233        NAL                              Not allocated
234        NAP                             Not applicable
235        NRP                                No response
236        NSP                              Not specified
237        UNK                                    Unknown

[238 rows x 2 columns]

In [6]:
# Find reporter codes by country name
api.codes("geo", search="denmark")

                        id                                              label
0           EU27_2020_X_DK  European Union - 27 countries (from 2020) exce...
1                       DK                                            Denmark
2  EU27_2020_NEA21_X_DK_SE  EU27 countries (from 2020) not in EA21 (from 2...
3  EU27_2020_NEA20_X_DK_SE  EU27 countries (from 2020) not in EA20 (2023-2...

In [7]:
# Browse EBOPS service categories
api.codes("bop_item", search="services")

         id                                              label
0        GS                                 Goods and services
1     GSIN1                 Goods, services and primary income
2         S                                           Services
3       ISS             International supply of services (ISS)
4        SA  Services: manufacturing services on physical i...
..      ...                                                ...
147   SL33X  Memo item: services, government services: othe...
148     SOX                      Services: commercial services
149      SN                   Services: services not allocated
150  S_X_CG  Services excluding transport and financial ser...
151   OTH_S                                     Other services

[152 rows x 2 columns]

In [8]:
# Search for a specific service type
api.codes("bop_item", search="transport")

        id                                              label
0       SC                                Services: transport
1      SC1                            Services: sea transport
2     SC11                 Services: sea transport; passenger
3     SC12                   Services: sea transport; freight
4     SC13  Services: sea transport; other than passenger ...
5      SC2                            Services: air transport
6     SC21                 Services: air transport; passenger
7     SC22                   Services: air transport; freight
8     SC23  Services: air transport; other than passenger ...
9      SC3                 Services: other modes of transport
10    SC31      Services: other modes of transport; passenger
11    SC32        Services: other modes of transport; freight
12    SC33  Services: other modes of transport; other than...
13    SC3A                          Services: space transport
14    SC3B                           Services: rail transport
15   SC3B1                Services: rail transport; passenger
16   SC3B2                  Services: rail transport; freight
17   SC3B3  Services: rail transport; other than passenger...
18    SC3C                           Services: road transport
19   SC3C1                Services: road transport; passenger
20   SC3C2                  Services: road transport; freight
21   SC3C3  Services: road transport; other than passenger...
22    SC3D                Services: inland waterway transport
23   SC3D1     Services: inland waterway transport; passenger
24   SC3D2       Services: inland waterway transport; freight
25   SC3D3  Services: inland waterway transport; other tha...
26    SC3E                       Services: pipeline transport
27    SC3G  Services: other supporting and auxiliary trans...
28     SCA        Services: all modes of transport; passenger
29    SCAZ  Services: all modes of transport; passenger; o...
30     SCB          Services: all modes of transport; freight
31     SCC  Services: all modes of transport; other than p...
32    SCC1  Services: all modes of transport; other than p...
33     SD2         Services: travel; local transport services
34     SD5  Services: travel; other services than goods (t...
35    SD5Y  Services: travel; other services than goods (t...
36    SD5Z  Services: travel; other services than goods (t...
37     SDZ  Services: tourism-related services in travel a...
38  S_X_CG  Services excluding transport and financial ser...

---
## 3. Fetch data

Use `+` to combine multiple values per dimension.

In [9]:
df = api.get_data(
    geo          = "DK+DE+FR",
    partner      = "WRL_REST",   # rest of world — check api.codes('partner', aggregates_only=True)
    bop_item     = "S",          # total services
    stk_flow     = "CRE+DEB",   # credit (exports) + debit (imports)
    currency     = "MIO_EUR",
    start_period = "2015",
    end_period   = "2023",
)

df

   freq currency bop_item stk_flow   partner geo period     value
0     A  MIO_EUR        S      CRE  WRL_REST  DK   2015   58384.0
1     A  MIO_EUR        S      CRE  WRL_REST  DK   2016   57751.2
2     A  MIO_EUR        S      CRE  WRL_REST  DK   2017   64111.0
3     A  MIO_EUR        S      CRE  WRL_REST  DK   2018   70279.1
4     A  MIO_EUR        S      CRE  WRL_REST  DK   2019   74704.6
5     A  MIO_EUR        S      CRE  WRL_REST  DK   2020   67072.3
6     A  MIO_EUR        S      CRE  WRL_REST  DK   2021   84870.4
7     A  MIO_EUR        S      CRE  WRL_REST  DK   2022  129014.5
8     A  MIO_EUR        S      CRE  WRL_REST  DK   2023  111623.4
9     A  MIO_EUR        S      CRE  WRL_REST  DE   2015  258520.0
10    A  MIO_EUR        S      CRE  WRL_REST  DE   2016  270545.0
11    A  MIO_EUR        S      CRE  WRL_REST  DE   2017  290027.0
12    A  MIO_EUR        S      CRE  WRL_REST  DE   2018  308653.0
13    A  MIO_EUR        S      CRE  WRL_REST  DE   2019  327246.0
14    A  MIO_EUR        S      CRE  WRL_REST  DE   2020  292006.0
15    A  MIO_EUR        S      CRE  WRL_REST  DE   2021  348863.0
16    A  MIO_EUR        S      CRE  WRL_REST  DE   2022  419691.0
17    A  MIO_EUR        S      CRE  WRL_REST  DE   2023  418631.0
18    A  MIO_EUR        S      CRE  WRL_REST  FR   2015  230471.0
19    A  MIO_EUR        S      CRE  WRL_REST  FR   2016  234148.0
20    A  MIO_EUR        S      CRE  WRL_REST  FR   2017  242931.0
21    A  MIO_EUR        S      CRE  WRL_REST  FR   2018  256348.0
22    A  MIO_EUR        S      CRE  WRL_REST  FR   2019  264183.0
23    A  MIO_EUR        S      CRE  WRL_REST  FR   2020  215078.0
24    A  MIO_EUR        S      CRE  WRL_REST  FR   2021  267513.0
25    A  MIO_EUR        S      CRE  WRL_REST  FR   2022  345712.0
26    A  MIO_EUR        S      CRE  WRL_REST  FR   2023  346396.0
27    A  MIO_EUR        S      DEB  WRL_REST  DK   2015   53587.8
28    A  MIO_EUR        S      DEB  WRL_REST  DK   2016   55822.8
29    A  MIO_EUR        S      DEB  WRL_REST  DK   2017   58277.5
30    A  MIO_EUR        S      DEB  WRL_REST  DK   2018   65443.3
31    A  MIO_EUR        S      DEB  WRL_REST  DK   2019   71476.4
32    A  MIO_EUR        S      DEB  WRL_REST  DK   2020   65178.8
33    A  MIO_EUR        S      DEB  WRL_REST  DK   2021   73711.3
34    A  MIO_EUR        S      DEB  WRL_REST  DK   2022  101569.6
35    A  MIO_EUR        S      DEB  WRL_REST  DK   2023  106191.9
36    A  MIO_EUR        S      DEB  WRL_REST  DE   2015  274755.0
37    A  MIO_EUR        S      DEB  WRL_REST  DE   2016  288890.0
38    A  MIO_EUR        S      DEB  WRL_REST  DE   2017  311238.0
39    A  MIO_EUR        S      DEB  WRL_REST  DE   2018  322664.0
40    A  MIO_EUR        S      DEB  WRL_REST  DE   2019  341689.0
41    A  MIO_EUR        S      DEB  WRL_REST  DE   2020  285373.0
42    A  MIO_EUR        S      DEB  WRL_REST  DE   2021  345030.0
43    A  MIO_EUR        S      DEB  WRL_REST  DE   2022  451726.0
44    A  MIO_EUR        S      DEB  WRL_REST  DE   2023  482069.0
45    A  MIO_EUR        S      DEB  WRL_REST  FR   2015  210374.0
46    A  MIO_EUR        S      DEB  WRL_REST  FR   2016  213924.0
47    A  MIO_EUR        S      DEB  WRL_REST  FR   2017  218484.0
48    A  MIO_EUR        S      DEB  WRL_REST  FR   2018  232005.0
49    A  MIO_EUR        S      DEB  WRL_REST  FR   2019  238570.0
50    A  MIO_EUR        S      DEB  WRL_REST  FR   2020  198981.0
51    A  MIO_EUR        S      DEB  WRL_REST  FR   2021  227524.0
52    A  MIO_EUR        S      DEB  WRL_REST  FR   2022  277616.0
53    A  MIO_EUR        S      DEB  WRL_REST  FR   2023  306913.0

In [10]:
# Quick pivot: period x geo, exports only
exports = df[df["stk_flow"] == "CRE"].pivot_table(
    index="period", columns="geo", values="value"
)
exports

geo           DE        DK        FR
period
2015    258520.0   58384.0  230471.0
2016    270545.0   57751.2  234148.0
2017    290027.0   64111.0  242931.0
2018    308653.0   70279.1  256348.0
2019    327246.0   74704.6  264183.0
2020    292006.0   67072.3  215078.0
2021    348863.0   84870.4  267513.0
2022    419691.0  129014.5  345712.0
2023    418631.0  111623.4  346396.0

---
## 4. Multi-item query from a list

Use `"+".join(...)` to build the key string from a Python list.

In [11]:
# Sub-categories of services — check api.codes('bop_item') for full list
items = ["SC", "SD", "SE"]   # transport, travel, other services
geos  = ["DK", "DE", "FR", "SE"]

item_key = "+".join(items)
geo_key  = "+".join(geos)

df2 = api.get_data(
    geo          = geo_key,
    partner      = "WRL_REST",
    bop_item     = item_key,
    stk_flow     = "CRE+DEB",
    currency     = "MIO_EUR",
    start_period = "2015",
    end_period   = "2023",
)

df2

    freq currency bop_item stk_flow   partner geo period    value
0      A  MIO_EUR       SC      CRE  WRL_REST  DK   2015  33054.2
1      A  MIO_EUR       SC      CRE  WRL_REST  DK   2016  29504.5
2      A  MIO_EUR       SC      CRE  WRL_REST  DK   2017  33222.4
3      A  MIO_EUR       SC      CRE  WRL_REST  DK   2018  35837.5
4      A  MIO_EUR       SC      CRE  WRL_REST  DK   2019  39682.0
..   ...      ...      ...      ...       ...  ..    ...      ...
211    A  MIO_EUR       SE      DEB  WRL_REST  SE   2019   1771.9
212    A  MIO_EUR       SE      DEB  WRL_REST  SE   2020   1268.4
213    A  MIO_EUR       SE      DEB  WRL_REST  SE   2021   1459.6
214    A  MIO_EUR       SE      DEB  WRL_REST  SE   2022   1731.5
215    A  MIO_EUR       SE      DEB  WRL_REST  SE   2023   1516.5

[216 rows x 8 columns]